import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseAnonKey);

const sections = [
  ['overview','نظرة عامة'],['settings','إعدادات التطبيق'],['books','الكتب'],['magazines','المجلات'],['issues','الأعداد'],['library','أقسام المكتبة'],['news','شريط الأخبار'],['codes','أكواد التفعيل'],['maintenance','الصيانة']
];

function App(){
 const [session,setSession]=useState(null); const [page,setPage]=useState('overview'); const [error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[]);
 if(!session) return <Login error={error} onError={setError}/>;
 return <Dashboard page={page} setPage={setPage} session={session} onLogout={()=>supabase.auth.signOut()} onError={setError} error={error}/>;
}
function Login({error,onError}){ const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);onError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)onError('بيانات الدخول غير صحيحة أو الحساب غير مخوّل.');setBusy(false)} return <main className="login"><form onSubmit={submit}><h1>KITARA Control</h1><p>لوحة التحكم المركزية لكِتارا</p><input type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?'جارٍ الدخول...':'دخول'}</button>{error&&<div className="error">{error}</div>}</form></main> }
function Dashboard({page,setPage,session,onLogout,onError,error}){return <div className="shell"><aside><div className="brand">KITARA<br/><small>Control</small></div>{sections.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}<button className="logout" onClick={onLogout}>تسجيل الخروج</button></aside><main className="content"><header><div><h2>{sections.find(x=>x[0]===page)?.[1]}</h2><small>{session.user.email}</small></div></header>{error&&<div className="error banner">{error}</div>}<Page page={page} onError={onError}/></main></div>}
function Page({page,onError}){ if(page==='overview')return <Overview/>; if(page==='settings')return <Settings onError={onError}/>; if(page==='books')return <Crud table="books" fields={bookFields} title="الكتب" onError={onError}/>; if(page==='magazines')return <Crud table="magazines" fields={magazineFields} title="المجلات" onError={onError}/>; if(page==='issues')return <Crud table="magazine_issues" fields={issueFields} title="الأعداد" onError={onError}/>; if(page==='library')return <Crud table="library_sections" fields={libraryFields} title="أقسام المكتبة" onError={onError}/>; if(page==='news')return <Crud table="news_ticker" fields={newsFields} title="شريط الأخبار" onError={onError}/>; if(page==='codes')return <Codes onError={onError}/>; if(page==='maintenance')return <Settings filter="maintenance" onError={onError}/>; return null }
const bookFields=[['title','العنوان'],['author','المؤلف'],['description','الوصف'],['category','القسم'],['cover_url','رابط الغلاف'],['download_url','رابط التنزيل'],['is_magazine','مجلة','bool'],['is_exclusive','حصري','bool']];
const magazineFields=[['name','اسم المجلة'],['description','الوصف'],['cover_url','رابط الغلاف']];
const issueFields=[['magazine_id','معرّف المجلة'],['issue_number','رقم العدد','number'],['title','العنوان'],['description','الوصف'],['cover_url','رابط الغلاف'],['download_url','رابط التنزيل'],['is_exclusive','حصري','bool']];
const libraryFields=[['section_key','المفتاح'],['title','العنوان'],['subtitle','الوصف المختصر'],['icon_name','اسم الأيقونة'],['sort_order','الترتيب','number'],['is_active','نشط','bool']];
const newsFields=[['text','النص'],['is_active','نشط','bool'],['sort_order','الترتيب','number']];
function Overview(){return <div className="grid cards"><Card title="التحكم المركزي" text="إدارة إعدادات التطبيق والمحتوى دون إعادة بناء APK."/><Card title="المحتوى" text="إضافة وتعديل وحذف الكتب والمجلات والأعداد والأقسام."/><Card title="المظهر" text="تعديل النصوص والألوان وأجزاء الواجهة من الإعدادات البعيدة."/><Card title="التشغيل" text="إدارة الصيانة، المحتوى الحصري، وشريط الأخبار."/></div>}
function Card({title,text}){return <div className="card"><h3>{title}</h3><p>{text}</p></div>}
async function loadTable(table){const {data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}
function Crud({table,fields,title,onError}){const [rows,setRows]=useState([]);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(true);async function reload(){setBusy(true);const {data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false});if(error)onError(error.message);else setRows(data||[]);setBusy(false)}useEffect(()=>{reload()},[]);async function save(values){const payload={...values};fields.forEach(([k,,t])=>{if(t==='number')payload[k]=Number(payload[k]);if(t==='bool')payload[k]=!!payload[k]});let result;if(editing?.id)result=await supabase.from(table).update(payload).eq('id',editing.id);else result=await supabase.from(table).insert(payload);if(result.error)onError(result.error.message);else{setEditing(null);await reload()}}async function remove(id){if(!confirm('هل تريد الحذف؟'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)onError(error.message);else reload()}return <div className="panel"><div className="toolbar"><button onClick={()=>setEditing({})}>إضافة جديد</button><span>{busy?'جارٍ التحميل...':`${rows.length} عنصر`}</span></div>{editing!==null&&<Editor fields={fields} row={editing} onCancel={()=>setEditing(null)} onSave={save}/>}<div className="table">{rows.map(row=><div className="row" key={row.id}><div className="rowmain"><strong>{row.title||row.name||row.text||row.section_key||`#${row.issue_number}`}</strong><small>{row.category||row.description||row.download_url||''}</small></div><div><button onClick={()=>setEditing(row)}>تعديل</button><button className="danger" onClick={()=>remove(row.id)}>حذف</button></div></div>)}</div></div>}
function Editor({fields,row,onCancel,onSave}){const [v,setV]=useState(()=>Object.fromEntries(fields.map(([k,,t])=>[k,row[k]??(t==='bool'?false:'')] )));return <div className="editor">{fields.map(([k,label,t])=>t==='bool'?<label className="check" key={k}><input type="checkbox" checked={!!v[k]} onChange={e=>setV({...v,[k]:e.target.checked})}/>{label}</label>:<label key={k}>{label}<input type={t==='number'?'number':'text'} value={v[k]??''} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}<div className="actions"><button onClick={()=>onSave(v)}>حفظ</button><button onClick={onCancel}>إلغاء</button></div></div>}
function Settings({filter,onError}){const [items,setItems]=useState([]);const [values,setValues]=useState({});const [busy,setBusy]=useState(true);useEffect(()=>{supabase.from('app_settings').select('*').order('key').then(({data,error})=>{if(error)onError(error.message);else{const list=(data||[]).filter(x=>!filter||x.key.startsWith('maintenance_'));setItems(list);setValues(Object.fromEntries(list.map(x=>[x.key,x.value])))}setBusy(false)})},[]);async function save(key){const {error}=await supabase.from('app_settings').upsert({key,value:values[key]??''},{onConflict:'key'});if(error)onError(error.message)}return <div className="panel"><div className="toolbar"><span>{busy?'جارٍ التحميل...':'الإعدادات البعيدة'}</span></div>{items.map(x=><div className="setting" key={x.key}><label><strong>{x.key}</strong><input value={values[x.key]??''} onChange={e=>setValues({...values,[x.key]:e.target.value})}/></label><button onClick={()=>save(x.key)}>حفظ</button></div>)}</div>}
function Codes({onError}){return <Crud table="kitara_activation_codes" fields={[["code","الكود"],["is_active","نشط","bool"]]} title="أكواد التفعيل" onError={onError}/>}

createRoot(document.getElementById('root')).render(<App/>);
