import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

// The Supabase URL and publishable key are safe for a browser client.
// Environment variables can override these defaults when the admin panel is deployed elsewhere.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://gftlkxpzympplwluxmah.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_ZzcG37T_pgUGeAt_J6gr3w_ocfDTb9I';
const supabase = createClient(supabaseUrl, supabaseAnonKey);

const sections = [
  ['overview','نظرة عامة'],['settings','إعدادات التطبيق'],['books','الكتب'],['book-codes','أكواد الكتب'],['magazines','المجلات'],['issues','الأعداد'],['library','أقسام المكتبة'],['news','شريط الأخبار'],['codes','أكواد التفعيل'],['maintenance','الصيانة']
];

function App(){
 const [session,setSession]=useState(null); const [authorized,setAuthorized]=useState(false); const [checking,setChecking]=useState(true); const [page,setPage]=useState('overview'); const [error,setError]=useState('');
 useEffect(()=>{let mounted=true; supabase.auth.getSession().then(async({data})=>{if(!mounted)return; setSession(data.session); if(data.session) await checkAdmin(data.session); else setChecking(false)}); const {data}=supabase.auth.onAuthStateChange(async(_e,s)=>{if(!mounted)return; setSession(s); if(s) await checkAdmin(s); else {setAuthorized(false);setChecking(false)}}); return()=>{mounted=false;data.subscription.unsubscribe()};},[]);
 async function checkAdmin(s){setChecking(true); const {data,error}=await supabase.rpc('is_kitara_admin'); if(error||data!==true){setAuthorized(false);setError('هذا الحساب غير مخوّل للوصول إلى لوحة KITARA Control.'); await supabase.auth.signOut();}else{setAuthorized(true);setError('')} setChecking(false)}
 if(checking) return <main className="login"><div className="login formlike"><h1>KITARA Control</h1><p>جارٍ التحقق من صلاحيات المدير...</p></div></main>;
 if(!session||!authorized) return <Login error={error} onError={setError}/>;
 return <Dashboard page={page} setPage={setPage} session={session} onLogout={()=>supabase.auth.signOut()} onError={setError} error={error}/>;
}
function Login({error,onError}){ const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);onError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)onError('بيانات الدخول غير صحيحة أو الحساب غير مخوّل.');setBusy(false)} return <main className="login"><form onSubmit={submit}><h1>KITARA Control</h1><p>لوحة التحكم المركزية لكِتارا</p><input type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?'جارٍ الدخول...':'دخول'}</button>{error&&<div className="error">{error}</div>}</form></main> }
function Dashboard({page,setPage,session,onLogout,onError,error}){return <div className="shell"><aside><div className="brand">KITARA<br/><small>Control</small></div>{sections.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);onError('')}}>{label}</button>)}<button className="logout" onClick={onLogout}>تسجيل الخروج</button></aside><main className="content"><header><div><h2>{sections.find(x=>x[0]===page)?.[1]}</h2><small>{session.user.email}</small></div></header>{error&&<div className="error banner">{error}</div>}<Page page={page} onError={onError}/></main></div>}
function Page({page,onError}){ if(page==='overview')return <Overview/>; if(page==='settings')return <Settings onError={onError}/>; if(page==='books')return <Crud table="books" fields={bookFields} title="الكتب" onError={onError}/>; if(page==='book-codes')return <BookCodes onError={onError}/>; if(page==='magazines')return <Crud table="magazines" fields={magazineFields} title="المجلات" onError={onError}/>; if(page==='issues')return <Crud table="magazine_issues" fields={issueFields} title="الأعداد" onError={onError}/>; if(page==='library')return <Crud table="library_sections" fields={libraryFields} title="أقسام المكتبة" onError={onError}/>; if(page==='news')return <Crud table="news_ticker" fields={newsFields} title="شريط الأخبار" onError={onError}/>; if(page==='codes')return <Crud table="kitara_activation_codes" fields={activationFields} title="أكواد التفعيل" onError={onError}/>; if(page==='maintenance')return <Settings filter="maintenance" onError={onError}/>; return null }
const bookFields=[['title','العنوان'],['author','المؤلف'],['description','الوصف','textarea'],['category','القسم'],['cover_url','رابط الغلاف'],['download_url','رابط التنزيل'],['is_magazine','مجلة','bool'],['is_exclusive','حصري','bool']];
const magazineFields=[['name','اسم المجلة'],['description','الوصف','textarea'],['cover_url','رابط الغلاف']];
const issueFields=[['magazine_id','معرّف المجلة'],['issue_number','رقم العدد','number'],['title','العنوان'],['description','الوصف','textarea'],['cover_url','رابط الغلاف'],['download_url','رابط التنزيل'],['is_exclusive','حصري','bool']];
const libraryFields=[['section_key','المفتاح'],['title','العنوان'],['subtitle','الوصف المختصر'],['icon_name','اسم الأيقونة'],['sort_order','الترتيب','number'],['is_active','نشط','bool']];
const newsFields=[['text','النص','textarea'],['is_active','نشط','bool'],['sort_order','الترتيب','number']];
const activationFields=[['code','الكود'],['is_active','نشط','bool']];
function Overview(){return <div className="grid cards"><Card title="التحكم المركزي" text="إدارة إعدادات التطبيق والمحتوى دون إعادة بناء APK."/><Card title="المحتوى" text="إضافة وتعديل وحذف الكتب والمجلات والأعداد والأقسام وأكواد المحتوى."/><Card title="المظهر" text="تعديل النصوص والألوان وأجزاء الواجهة من الإعدادات البعيدة."/><Card title="التشغيل" text="إدارة الصيانة والمحتوى الحصري وشريط الأخبار وأكواد التفعيل."/></div>}
function Card({title,text}){return <div className="card"><h3>{title}</h3><p>{text}</p></div>}
function Crud({table,fields,title,onError}){const [rows,setRows]=useState([]);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(true);async function reload(){setBusy(true);const {data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false});if(error)onError(error.message);else setRows(data||[]);setBusy(false)}useEffect(()=>{reload()},[]);async function save(values){const payload={...values};fields.forEach(([k,,t])=>{if(t==='number')payload[k]=Number(payload[k]);if(t==='bool')payload[k]=!!payload[k]});let result;if(editing?.id)result=await supabase.from(table).update(payload).eq('id',editing.id);else result=await supabase.from(table).insert(payload);if(result.error)onError(result.error.message);else{setEditing(null);onError('');await reload()}}async function remove(id){if(!confirm('هل تريد الحذف؟'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)onError(error.message);else{onError('');reload()}}return <div className="panel"><div className="toolbar"><button onClick={()=>setEditing({})}>إضافة جديد</button><span>{busy?'جارٍ التحميل...':`${rows.length} عنصر`}</span></div>{editing!==null&&<Editor fields={fields} row={editing} onCancel={()=>setEditing(null)} onSave={save}/>}<div className="table">{rows.map(row=><div className="row" key={row.id}><div className="rowmain"><strong>{row.title||row.name||row.text||row.section_key||`#${row.issue_number}`}</strong><small>{row.category||row.description||row.download_url||row.code||''}</small></div><div><button onClick={()=>setEditing(row)}>تعديل</button><button className="danger" onClick={()=>remove(row.id)}>حذف</button></div></div>)}</div></div>}
function Editor({fields,row,onCancel,onSave}){const [v,setV]=useState(()=>Object.fromEntries(fields.map(([k,,t])=>[k,row[k]??(t==='bool'?false:'')] )));return <div className="editor">{fields.map(([k,label,t])=>t==='bool'?<label className="check" key={k}><input type="checkbox" checked={!!v[k]} onChange={e=>setV({...v,[k]:e.target.checked})}/>{label}</label>:<label key={k}>{label}{t==='textarea'?<textarea rows="4" value={v[k]??''} onChange={e=>setV({...v,[k]:e.target.value})}/>:<input type={t==='number'?'number':'text'} value={v[k]??''} onChange={e=>setV({...v,[k]:e.target.value})}/>}</label>)}<div className="actions"><button onClick={()=>onSave(v)}>حفظ</button><button onClick={onCancel}>إلغاء</button></div></div>}
function Settings({filter,onError}){const [items,setItems]=useState([]);const [values,setValues]=useState({});const [newKey,setNewKey]=useState('');const [newValue,setNewValue]=useState('');const [busy,setBusy]=useState(true);async function reload(){setBusy(true);const {data,error}=await supabase.from('app_settings').select('*').order('key');if(error)onError(error.message);else{const list=(data||[]).filter(x=>!filter||x.key.startsWith('maintenance_'));setItems(list);setValues(Object.fromEntries(list.map(x=>[x.key,x.value])))}setBusy(false)}useEffect(()=>{reload()},[]);async function save(key){const {error}=await supabase.from('app_settings').upsert({key,value:values[key]??''},{onConflict:'key'});if(error)onError(error.message);else{onError('');reload()}}async function add(){const key=newKey.trim();if(!key)return;const {error}=await supabase.from('app_settings').upsert({key,value:newValue},{onConflict:'key'});if(error)onError(error.message);else{setNewKey('');setNewValue('');onError('');reload()}}async function remove(key){if(!confirm('حذف هذا الإعداد؟'))return;const {error}=await supabase.from('app_settings').delete().eq('key',key);if(error)onError(error.message);else{onError('');reload()}}return <div className="panel"><div className="toolbar"><span>{busy?'جارٍ التحميل...':'الإعدادات البعيدة'}</span></div><div className="setting new-setting"><label><strong>مفتاح جديد</strong><input value={newKey} onChange={e=>setNewKey(e.target.value)} placeholder="مثال: welcome_title"/></label><label><strong>القيمة</strong><input value={newValue} onChange={e=>setNewValue(e.target.value)}/></label><button onClick={add}>إضافة</button></div>{items.map(x=><div className="setting" key={x.key}><label><strong>{x.key}</strong><input value={values[x.key]??''} onChange={e=>setValues({...values,[x.key]:e.target.value})}/></label><button onClick={()=>save(x.key)}>حفظ</button><button className="danger" onClick={()=>remove(x.key)}>حذف</button></div>)}</div>}
function BookCodes({onError}){const [books,setBooks]=useState([]);const [selected,setSelected]=useState('');const [code,setCode]=useState('');const [active,setActive]=useState(true);const [rows,setRows]=useState([]);async function load(){const [{data:b,error:be},{data:c,error:ce}]=await Promise.all([supabase.from('books').select('id,title').order('title'),supabase.from('book_access_codes').select('*').order('created_at',{ascending:false})]);if(be)onError(be.message);else setBooks(b||[]);if(ce)onError(ce.message);else setRows(c||[])}useEffect(()=>{load()},[]);async function add(){if(!selected||!code.trim())return;const {error}=await supabase.from('book_access_codes').insert({book_id:selected,access_code:code.trim(),is_active:active});if(error)onError(error.message);else{setCode('');onError('');load()}}async function toggle(row){const {error}=await supabase.from('book_access_codes').update({is_active:!row.is_active}).eq('id',row.id);if(error)onError(error.message);else load()}async function remove(id){if(!confirm('هل تريد الحذف؟'))return;const {error}=await supabase.from('book_access_codes').delete().eq('id',id);if(error)onError(error.message);else load()}return <div className="panel"><div className="editor"><label>الكتاب<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر كتابًا</option>{books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label>كود الوصول<input value={code} onChange={e=>setCode(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>نشط</label><div className="actions"><button onClick={add}>إضافة الكود</button></div></div><div className="table">{rows.map(r=><div className="row" key={r.id}><div className="rowmain"><strong>{books.find(b=>b.id===r.book_id)?.title||r.book_id}</strong><small>{r.access_code}</small></div><div><button onClick={()=>toggle(r)}>{r.is_active?'تعطيل':'تفعيل'}</button><button className="danger" onClick={()=>remove(r.id)}>حذف</button></div></div>)}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
