name: kitara
description: KITARA - كِتارا، تطبيق عربي للكتب والمجلات المرخصة.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.15.4
  audioplayers: ^6.4.0
  google_mobile_ads: ^6.0.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/kitara_intro.wav
    - assets/kitara_icon.png
    - assets/fonts/amiri-regular.ttf
    - assets/fonts/amiri-bold.ttf

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri-regular.ttf
        - asset: assets/fonts/amiri-bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/kitara_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/kitara_icon.png"
